# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: item.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'item.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nitem.proto\x12\x04item\"0\n\x0bItemRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\"+\n\x0cItemResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"5\n\x04Item\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\"%\n\x08ItemList\x12\x19\n\x05items\x18\x01 \x03(\x0b\x32\n.item.Item\"\x07\n\x05\x45mpty2k\n\x0bItemService\x12\x33\n\nCreateItem\x12\x11.item.ItemRequest\x1a\x12.item.ItemResponse\x12\'\n\x08GetItems\x12\x0b.item.Empty\x1a\x0e.item.ItemListb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'item_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ITEMREQUEST']._serialized_start=20
  _globals['_ITEMREQUEST']._serialized_end=68
  _globals['_ITEMRESPONSE']._serialized_start=70
  _globals['_ITEMRESPONSE']._serialized_end=113
  _globals['_ITEM']._serialized_start=115
  _globals['_ITEM']._serialized_end=168
  _globals['_ITEMLIST']._serialized_start=170
  _globals['_ITEMLIST']._serialized_end=207
  _globals['_EMPTY']._serialized_start=209
  _globals['_EMPTY']._serialized_end=216
  _globals['_ITEMSERVICE']._serialized_start=218
  _globals['_ITEMSERVICE']._serialized_end=325
# @@protoc_insertion_point(module_scope)
