repos:
  - repo: local
    hooks:
      - id: eslint-prettier-check
        name: ESLint + Prettier
        entry: ./run_eslint.sh
        language: script
        types: [javascript, jsx, ts, tsx]
        always_run: true


      - id: ruff-check-format
        name: Run Ruff lint + format on backend Python files
        entry: ./run_ruff.sh
        language: system
        types: [python]
        pass_filenames: true
