version: '3.9'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./frontend/dist:/usr/share/nginx/html
    depends_on:
      - backend
      - mediamtx
    networks:
      - app-net

  frontend:
    build: ./frontend
    networks:
      - app-net

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - app-net

  mediamtx:
    image: bluenviron/mediamtx:latest
    volumes:
      - ./mediamtx.yml:/etc/mediamtx.yml
    ports:
      - "8888:8888" # HTTP
      - "8889:8889" # WebRTC
      - "8554:8554" # RTSP
    networks:
      - app-net
  
  ffmpeg:
    image: jrottenberg/ffmpeg:latest
    command: >
      -re -stream_loop -1 -i /media/input.mp4 
      -c:v libx264 -preset veryfast -b:v 2000k
      -c:a aac -ar 44100 -b:a 128k 
      -f rtsp rtsp://mediamtx:8554/mystream
    volumes:
      - ./media:/media
    depends_on:
      - mediamtx
    networks:
      - app-net

      
networks:
  app-net:
    driver: bridge

