use async_nats::connect;
use serde::Serialize;
use std::time::Duration;
use tokio::time::sleep;

#[derive(Serialize)]
struct Notification {
    id: u64,
    message: String,
    timestamp: String,
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    let client = connect("nats://nats:4222").await?;

    let total_duration = Duration::from_secs(60 * 9); // 9 minutes
    let interval = Duration::from_secs(15);
    let mut elapsed = Duration::from_secs(0);
    let mut counter = 1;

    while elapsed < total_duration {
        let notification = Notification {
            id: counter,
            message: format!("Generated by Rust! Notification #{}", counter),
            timestamp: chrono::Utc::now().to_rfc3339(),
        };

        let payload = serde_json::to_vec(&notification)?;
        client.publish("data.notifications", payload.into()).await?;

        println!("Sent notification #{}", counter);
        sleep(interval).await;
        elapsed += interval;
        counter += 1;
    }

    Ok(())
}
