# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: grpc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'grpc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngrpc.proto\"\x1d\n\x0cTopicRequest\x12\r\n\x05topic\x18\x01 \x01(\t\"\x1c\n\x0cTopicMessage\x12\x0c\n\x04\x64\x61ta\x18\x01 \x01(\t2;\n\nSubscriber\x12-\n\tSubscribe\x12\r.TopicRequest\x1a\r.TopicMessage\"\x00\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TOPICREQUEST']._serialized_start=14
  _globals['_TOPICREQUEST']._serialized_end=43
  _globals['_TOPICMESSAGE']._serialized_start=45
  _globals['_TOPICMESSAGE']._serialized_end=73
  _globals['_SUBSCRIBER']._serialized_start=75
  _globals['_SUBSCRIBER']._serialized_end=134
# @@protoc_insertion_point(module_scope)
